target:
  census_version: stable
  organism: homo_sapiens

obs_filters:
  is_primary_data: true

  # Use plain labels for filtering
  disease: ["normal"]
  tissue_general: ["brain"]
  cell_type: ["T cell"]

  # Optional: narrow by assay or sex
  assay: ["10x 3' v2", "10x 3' v3", "10x multiome"]
  sex: ["male", "female"]

  # additional custom fragment if you need it
  # extra_value_filter: "development_stage != 'unknown'"

output:
  summary_csv: results.csv
